-- Remaining tickers

-- PRCT fix
UPDATE watchlist SET overall_score=46, overall_reasoning='PROCEPT BioRobotics hat mit dem Aquabeam-System die einzige wasserstrahl-basierte Roboterchirurgie und waechst >50% jaehrlich. Allerdings ist das Unternehmen noch nicht profitabel (PE -17.4), hat ein Einzelprodukt-Risiko, und die Market Cap von nur $1.5B macht es anfaellig fuer Volatilitaet. Die Konkurrenz durch Intuitive Surgical begrenzt das Potenzial trotz Uebernahmefantasie.', score_breakdown='{"fundamentals":{"kgv":1,"umsatz":7,"marge":2,"schulden":4,"total":14},"technicals":{"52w_abstand":5,"preistrend":4,"volumen":4,"total":13},"narrativ":{"these":6,"analysten":3,"katalysator":4,"total":13},"sentiment":{"upgrades":2,"insider":3,"social":2,"total":7},"bonus":{"multi_katalysator":1,"institutionell":1,"sektor":2,"total":4},"basis_score":51,"final_score":46}', star_violations='[{"level":"moderate","rule":"Nicht profitabel (PE -17.4) mit Einzelprodukt-Risiko","penalty":-5}]' WHERE ticker='PRCT';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('PRCT', date('now'), 46, 'PROCEPT BioRobotics hat mit dem Aquabeam die einzige wasserstrahl-basierte Roboterchirurgie und waechst >50% jaehrlich. Nicht profitabel (PE -17.4) und Einzelprodukt-Risiko. Uebernahmefantasie vorhanden aber Konkurrenz durch ISRG.', '{"fundamentals":{"kgv":1,"umsatz":7,"marge":2,"schulden":4,"total":14},"technicals":{"52w_abstand":5,"preistrend":4,"volumen":4,"total":13},"narrativ":{"these":6,"analysten":3,"katalysator":4,"total":13},"sentiment":{"upgrades":2,"insider":3,"social":2,"total":7},"bonus":{"multi_katalysator":1,"institutionell":1,"sektor":2,"total":4},"basis_score":51,"final_score":46}', '[{"level":"moderate","rule":"Nicht profitabel mit Einzelprodukt-Risiko","penalty":-5}]');

-- PSTG — Pure Storage (Score: 50)
UPDATE watchlist SET overall_score=50, overall_reasoning='Pure Storage erreichte das erste $1B-Quartal mit Revenue +20% YoY und RPO +40% auf $3.7B, aber der EPS-Miss von >40% und das Rebrand zu Everpure loesten einen 10% Kursrückfall aus. Das P/E von ~174x ist fuer einen Storage-Anbieter extrem hoch, und die 1touch-Akquisition sowie der Namenswechsel schaffen Execution-Unsicherheit. Die FY2027-Guidance liegt zwar ueber Konsens, aber die Maerkte bewerten den Uebergang skeptisch.', score_breakdown='{"fundamentals":{"kgv":2,"umsatz":6,"marge":4,"schulden":5,"total":17},"technicals":{"52w_abstand":5,"preistrend":3,"volumen":6,"total":14},"narrativ":{"these":6,"analysten":4,"katalysator":4,"total":14},"sentiment":{"upgrades":2,"insider":3,"social":3,"total":8},"bonus":{"multi_katalysator":2,"institutionell":1,"sektor":2,"total":5},"basis_score":58,"final_score":50}', star_violations='[{"level":"moderate","rule":"P/E 174x extrem hoch bei EPS-Miss","penalty":-8}]' WHERE ticker='PSTG';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('PSTG', date('now'), 50, 'Pure Storage erstes $1B-Quartal aber EPS-Miss >40%. Rebrand zu Everpure schafft Unsicherheit. P/E 174x extrem. FY27 Guidance ueber Konsens aber Execution-Risiko.', '{"fundamentals":{"kgv":2,"umsatz":6,"marge":4,"schulden":5,"total":17},"technicals":{"52w_abstand":5,"preistrend":3,"volumen":6,"total":14},"narrativ":{"these":6,"analysten":4,"katalysator":4,"total":14},"sentiment":{"upgrades":2,"insider":3,"social":3,"total":8},"bonus":{"multi_katalysator":2,"institutionell":1,"sektor":2,"total":5},"basis_score":58,"final_score":50}', '[{"level":"moderate","rule":"P/E 174x extrem hoch bei EPS-Miss","penalty":-8}]');

-- PWR — Quanta Services (Score: 70)
UPDATE watchlist SET overall_score=70, overall_reasoning='Quanta baut die elektrische Infrastruktur die Data Centers ans Netz bringt mit einem Rekord-Backlog von $44B (+27.5%) und Q4-EPS-Beat. UBS ($646) und Truist ($643) sind extrem bullish, und die 2026 EPS-Guidance von $12.65-$13.35 impliziert 20%+ Wachstum. Allerdings ist das P/E von 81x fuer einen Baukonzern steil, und Execution-Risiken bei Grossprojekten sowie Arbeitskraeftemangel bleiben reale Bedrohungen.', score_breakdown='{"fundamentals":{"kgv":3,"umsatz":6,"marge":5,"schulden":4,"total":18},"technicals":{"52w_abstand":5,"preistrend":5,"volumen":4,"total":14},"narrativ":{"these":7,"analysten":5,"katalysator":6,"total":18},"sentiment":{"upgrades":5,"insider":3,"social":3,"total":11},"bonus":{"multi_katalysator":3,"institutionell":3,"sektor":3,"total":9},"basis_score":70,"final_score":70}', star_violations='[]' WHERE ticker='PWR';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('PWR', date('now'), 70, 'Quanta baut die elektrische Infrastruktur fuer Data Centers mit $44B Rekord-Backlog. UBS $646 und Truist $643 Targets. EPS-Guidance +20% Growth. P/E 81x sportlich fuer Baukonzern.', '{"fundamentals":{"kgv":3,"umsatz":6,"marge":5,"schulden":4,"total":18},"technicals":{"52w_abstand":5,"preistrend":5,"volumen":4,"total":14},"narrativ":{"these":7,"analysten":5,"katalysator":6,"total":18},"sentiment":{"upgrades":5,"insider":3,"social":3,"total":11},"bonus":{"multi_katalysator":3,"institutionell":3,"sektor":3,"total":9},"basis_score":70,"final_score":70}', '[]');

-- RNSHF — Renishaw (Score: 50)
UPDATE watchlist SET overall_score=50, overall_reasoning='Renishaw ist ein britischer Spezialist fuer Praezisionsencoder und Neurochirurgie-Roboter mit kritischer Bedeutung fuer Robotergelenk-Positionserfassung. Die Aktie fiel stark von $51.68 auf $45.23 (-12.5% in einer Woche) und der OTC-Handel bietet mit nur 12 Shares Volumen quasi keine Liquiditaet. Die starke These wird durch praktische Zugangsprobleme und fehlende Katalysatoren neutralisiert.', score_breakdown='{"fundamentals":{"kgv":5,"umsatz":4,"marge":6,"schulden":6,"total":21},"technicals":{"52w_abstand":4,"preistrend":2,"volumen":1,"total":7},"narrativ":{"these":6,"analysten":2,"katalysator":4,"total":12},"sentiment":{"upgrades":2,"insider":3,"social":2,"total":7},"bonus":{"multi_katalysator":2,"institutionell":1,"sektor":3,"total":6},"basis_score":53,"final_score":50}', star_violations='[{"level":"moderate","rule":"OTC-Liquiditaet quasi null (12 Shares Volumen)","penalty":-3}]' WHERE ticker='RNSHF';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('RNSHF', date('now'), 50, 'Renishaw Praezisionsencoder fuer Robotik, aber OTC-Liquiditaet quasi null. Kurs -12.5% in einer Woche. Starke These neutralisiert durch Zugangsprobleme.', '{"fundamentals":{"kgv":5,"umsatz":4,"marge":6,"schulden":6,"total":21},"technicals":{"52w_abstand":4,"preistrend":2,"volumen":1,"total":7},"narrativ":{"these":6,"analysten":2,"katalysator":4,"total":12},"sentiment":{"upgrades":2,"insider":3,"social":2,"total":7},"bonus":{"multi_katalysator":2,"institutionell":1,"sektor":3,"total":6},"basis_score":53,"final_score":50}', '[{"level":"moderate","rule":"OTC quasi null Liquiditaet","penalty":-3}]');

-- ROK — Rockwell Automation (Score: 62)
UPDATE watchlist SET overall_score=62, overall_reasoning='Rockwell lieferte einen starken Q1-Beat (EPS $2.75 vs $2.46, Revenue +11.9% YoY) und Goldman upgradete von Sell auf Neutral mit $448 Target. Die Digital-Twin-Technologie und Software-Momentum treiben wiederkehrende Umsaetze. Allerdings ist der Konsens Hold-lastig (10 Hold vs 12 Buy), das P/E von ~45x ist hoch, und der 15% Global Tariff drueckte die Aktie 2.8%. Solider Automation-Leader ohne explosives Upside.', score_breakdown='{"fundamentals":{"kgv":4,"umsatz":5,"marge":5,"schulden":5,"total":19},"technicals":{"52w_abstand":5,"preistrend":5,"volumen":4,"total":14},"narrativ":{"these":6,"analysten":4,"katalysator":5,"total":15},"sentiment":{"upgrades":4,"insider":3,"social":3,"total":10},"bonus":{"multi_katalysator":2,"institutionell":2,"sektor":3,"total":7},"basis_score":65,"final_score":62}', star_violations='[{"level":"moderate","rule":"Hold-lastiger Konsens trotz hohem P/E","penalty":-3}]' WHERE ticker='ROK';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('ROK', date('now'), 62, 'Rockwell Q1-Beat EPS $2.75 vs $2.46. Goldman Upgrade zu Neutral/$448. Digital-Twin Momentum. P/E 45x hoch, Konsens Hold-lastig.', '{"fundamentals":{"kgv":4,"umsatz":5,"marge":5,"schulden":5,"total":19},"technicals":{"52w_abstand":5,"preistrend":5,"volumen":4,"total":14},"narrativ":{"these":6,"analysten":4,"katalysator":5,"total":15},"sentiment":{"upgrades":4,"insider":3,"social":3,"total":10},"bonus":{"multi_katalysator":2,"institutionell":2,"sektor":3,"total":7},"basis_score":65,"final_score":62}', '[{"level":"moderate","rule":"Hold-lastiger Konsens","penalty":-3}]');

-- STRL — Sterling Infrastructure (Score: 58)
UPDATE watchlist SET overall_score=58, overall_reasoning='Sterling Infrastructure ist ein Data-Center-Bau-Spezialist mit >30% YoY Umsatzwachstum und E-Infrastructure-Segment das explosiv waechst. Die Aktie handelt nahe Allzeithoch bei $434, was starkes Momentum zeigt. Allerdings ist die Bewertung am ATH sportlich, die Baubranche ist zyklisch, und Materialkosten sowie Fachkraeftemangel koennten Margen druecken. Solider Picks-and-Shovels-Play aber mit begrenztem Upside ab ATH.', score_breakdown='{"fundamentals":{"kgv":4,"umsatz":7,"marge":5,"schulden":5,"total":21},"technicals":{"52w_abstand":4,"preistrend":5,"volumen":4,"total":13},"narrativ":{"these":6,"analysten":3,"katalysator":5,"total":14},"sentiment":{"upgrades":2,"insider":3,"social":3,"total":8},"bonus":{"multi_katalysator":2,"institutionell":2,"sektor":3,"total":7},"basis_score":63,"final_score":58}', star_violations='[{"level":"moderate","rule":"Bewertung am ATH sportlich fuer zyklische Baubranche","penalty":-5}]' WHERE ticker='STRL';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('STRL', date('now'), 58, 'Sterling Infrastructure DC-Bau >30% Wachstum nahe ATH. Zyklische Baubranche, Materialkosten-Risiko. Solider Picks-and-Shovels-Play.', '{"fundamentals":{"kgv":4,"umsatz":7,"marge":5,"schulden":5,"total":21},"technicals":{"52w_abstand":4,"preistrend":5,"volumen":4,"total":13},"narrativ":{"these":6,"analysten":3,"katalysator":5,"total":14},"sentiment":{"upgrades":2,"insider":3,"social":3,"total":8},"bonus":{"multi_katalysator":2,"institutionell":2,"sektor":3,"total":7},"basis_score":63,"final_score":58}', '[{"level":"moderate","rule":"ATH Bewertung zyklisch","penalty":-5}]');

-- SYK — Stryker (Score: 60)
UPDATE watchlist SET overall_score=60, overall_reasoning='Stryker ist der Marktfuehrer bei OP-Robotern mit dem Mako-System und 3 Jahren Vorsprung, mit Guidance fuer 8-9.5% organisches Wachstum 2026. Die Aktie handelt aber mit 89% Praemie zur Morningstar Fair Value, was das Upside stark limitiert. Mako-Installationen wachsen zweistellig und die Expansion in Wirbelsaeulen-OPs ist ein Katalysator, aber die hohe Bewertung und Healthcare-Regulierungsrisiken halten den Score im Interesting-Bereich.', score_breakdown='{"fundamentals":{"kgv":4,"umsatz":5,"marge":6,"schulden":5,"total":20},"technicals":{"52w_abstand":4,"preistrend":5,"volumen":4,"total":13},"narrativ":{"these":6,"analysten":4,"katalysator":5,"total":15},"sentiment":{"upgrades":3,"insider":3,"social":3,"total":9},"bonus":{"multi_katalysator":2,"institutionell":2,"sektor":2,"total":6},"basis_score":63,"final_score":60}', star_violations='[{"level":"moderate","rule":"89% Praemie zur Fair Value laut Morningstar","penalty":-3}]' WHERE ticker='SYK';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('SYK', date('now'), 60, 'Stryker Mako OP-Roboter Marktfuehrer. 8-9.5% org. Wachstum 2026. 89% Praemie zur Fair Value limitiert Upside. Expansion Wirbelsaeulen-OPs.', '{"fundamentals":{"kgv":4,"umsatz":5,"marge":6,"schulden":5,"total":20},"technicals":{"52w_abstand":4,"preistrend":5,"volumen":4,"total":13},"narrativ":{"these":6,"analysten":4,"katalysator":5,"total":15},"sentiment":{"upgrades":3,"insider":3,"social":3,"total":9},"bonus":{"multi_katalysator":2,"institutionell":2,"sektor":2,"total":6},"basis_score":63,"final_score":60}', '[{"level":"moderate","rule":"89% Praemie Fair Value","penalty":-3}]');

-- SYM — Symbotic (Score: 44)
UPDATE watchlist SET overall_score=44, overall_reasoning='Symbotic erreichte erstmals GAAP-Profitabilitaet ($13M) mit 29% Umsatzwachstum und 73% Software-Bruttomarge, was ein Wendepunkt sein koennte. Allerdings stammen ~90% des Umsatzes von Walmart (extremes Klumpenrisiko), Amazon baut eine eigene Loesung, und die Aktie fiel von $57 auf $54 (-5% in einer Woche). Die GreenBox-Plattform hat Potenzial, aber die Abhaengigkeit von einem einzigen Kunden ist ein gravierendes Risiko.', score_breakdown='{"fundamentals":{"kgv":3,"umsatz":6,"marge":5,"schulden":5,"total":19},"technicals":{"52w_abstand":4,"preistrend":3,"volumen":4,"total":11},"narrativ":{"these":6,"analysten":3,"katalysator":4,"total":13},"sentiment":{"upgrades":2,"insider":3,"social":3,"total":8},"bonus":{"multi_katalysator":1,"institutionell":1,"sektor":2,"total":4},"basis_score":55,"final_score":44}', star_violations='[{"level":"moderate","rule":"Schluesselkunde >50% Umsatzanteil (Walmart ~90%)","penalty":-10},{"level":"moderate","rule":"Amazon baut Konkurrenzloesung","penalty":-1}]' WHERE ticker='SYM';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('SYM', date('now'), 44, 'Symbotic erste GAAP-Profitabilitaet aber Walmart ~90% Umsatzanteil. Amazon baut eigene Loesung. GreenBox Potenzial vs Klumpenrisiko.', '{"fundamentals":{"kgv":3,"umsatz":6,"marge":5,"schulden":5,"total":19},"technicals":{"52w_abstand":4,"preistrend":3,"volumen":4,"total":11},"narrativ":{"these":6,"analysten":3,"katalysator":4,"total":13},"sentiment":{"upgrades":2,"insider":3,"social":3,"total":8},"bonus":{"multi_katalysator":1,"institutionell":1,"sektor":2,"total":4},"basis_score":55,"final_score":44}', '[{"level":"moderate","rule":"Walmart ~90% Umsatzanteil","penalty":-10},{"level":"moderate","rule":"Amazon Konkurrenz","penalty":-1}]');

-- TER — Teradyne (Score: 75)
UPDATE watchlist SET overall_score=75, overall_reasoning='Teradyne ist ein doppelter Gewinner: AI-Halbleiter-Test (>60% Revenue) plus Universal Robots als Cobot-Weltmarktfuehrer. Q4-EPS $1.80 schlug $1.36 um 32%, Revenue +44% YoY, und Q1-Guidance impliziert 75% YoY-Wachstum. Die MultiLane-JV staerkt die High-Speed-Test-Faehigkeiten fuer AI-Datacenter. Allerdings hat die Aktie nach dem Earnings-Surge von $343 auf $318 korrigiert (-7%), und die Bewertung ist nach +174% in 12 Monaten gestreckt.', score_breakdown='{"fundamentals":{"kgv":5,"umsatz":7,"marge":6,"schulden":6,"total":24},"technicals":{"52w_abstand":5,"preistrend":5,"volumen":6,"total":16},"narrativ":{"these":7,"analysten":5,"katalysator":6,"total":18},"sentiment":{"upgrades":4,"insider":3,"social":4,"total":11},"bonus":{"multi_katalysator":4,"institutionell":2,"sektor":3,"total":9},"basis_score":78,"final_score":75}', star_violations='[{"level":"moderate","rule":"Bewertung nach +174% in 12 Monaten gestreckt","penalty":-3}]' WHERE ticker='TER';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('TER', date('now'), 75, 'Teradyne doppelter Gewinner: AI-Test (>60% Rev) + Universal Robots Cobots. Q4 EPS beat 32%, Rev +44% YoY. MultiLane JV. Bewertung nach +174% gestreckt.', '{"fundamentals":{"kgv":5,"umsatz":7,"marge":6,"schulden":6,"total":24},"technicals":{"52w_abstand":5,"preistrend":5,"volumen":6,"total":16},"narrativ":{"these":7,"analysten":5,"katalysator":6,"total":18},"sentiment":{"upgrades":4,"insider":3,"social":4,"total":11},"bonus":{"multi_katalysator":4,"institutionell":2,"sektor":3,"total":9},"basis_score":78,"final_score":75}', '[{"level":"moderate","rule":"Bewertung gestreckt +174%","penalty":-3}]');

-- TLN — Talen Energy (Score: 68)
UPDATE watchlist SET overall_score=68, overall_reasoning='Talen Energy ist ein Nuclear-Power-Pure-Play mit dem massiven AWS-Deal (1.920 MW bis 2042, ~$18B Revenue) und 100% Strong Buy bei allen 7 Analysten mit Avg Target $481 (30% Upside). Forward P/E 17x bei 259% EPS-Wachstum YoY ist attraktiv bewertet fuer einen AI-Stromprofiteur. Allerdings fiel die Aktie 6% in einer Woche wegen Tarif-Aengsten, die hohe Verschuldung und regulatorisches Kernkraft-Risiko bleiben Ueberhang.', score_breakdown='{"fundamentals":{"kgv":6,"umsatz":5,"marge":5,"schulden":3,"total":19},"technicals":{"52w_abstand":5,"preistrend":4,"volumen":5,"total":14},"narrativ":{"these":7,"analysten":6,"katalysator":6,"total":19},"sentiment":{"upgrades":5,"insider":3,"social":4,"total":12},"bonus":{"multi_katalysator":3,"institutionell":3,"sektor":3,"total":9},"basis_score":73,"final_score":68}', star_violations='[{"level":"moderate","rule":"Hohe Verschuldung bei Kernkraft-Betreiber","penalty":-5}]' WHERE ticker='TLN';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('TLN', date('now'), 68, 'Talen Nuclear-Pure-Play mit AWS $18B-Deal. 100% Strong Buy, Avg Target $481. Forward PE 17x bei 259% EPS Growth. Hohe Verschuldung als Risiko.', '{"fundamentals":{"kgv":6,"umsatz":5,"marge":5,"schulden":3,"total":19},"technicals":{"52w_abstand":5,"preistrend":4,"volumen":5,"total":14},"narrativ":{"these":7,"analysten":6,"katalysator":6,"total":19},"sentiment":{"upgrades":5,"insider":3,"social":4,"total":12},"bonus":{"multi_katalysator":3,"institutionell":3,"sektor":3,"total":9},"basis_score":73,"final_score":68}', '[{"level":"moderate","rule":"Hohe Verschuldung","penalty":-5}]');

-- TRI — Thomson Reuters (Score: 66)
UPDATE watchlist SET overall_score=66, overall_reasoning='Thomson Reuters ist ein SaaSpocalypse-Opfer mit 57% Kursverlust vom Hoch, aber proprietaere Legal/Tax-Datenbanken und regulatorische Inhalte bilden einen tiefen Moat den AI nicht ersetzen kann. RBC upgradete auf Outperform/$126, und die Noetica-Akquisition fuer AI-native Deal Intelligence zeigt strategische Richtung. Allerdings schnitt JPMorgan drastisch auf $100, und der Anthropic Claude Legal-AI-Crash am 3.Feb (-15.8%) zeigt die reale Bedrohung. PE 24 mit 3% Dividende bietet Absicherung.', score_breakdown='{"fundamentals":{"kgv":6,"umsatz":4,"marge":6,"schulden":5,"total":21},"technicals":{"52w_abstand":7,"preistrend":6,"volumen":6,"total":19},"narrativ":{"these":7,"analysten":4,"katalysator":5,"total":16},"sentiment":{"upgrades":3,"insider":2,"social":3,"total":8},"bonus":{"multi_katalysator":2,"institutionell":2,"sektor":1,"total":5},"basis_score":69,"final_score":66}', star_violations='[{"level":"moderate","rule":"Anthropic Claude Legal-AI als strukturelle Bedrohung","penalty":-3}]' WHERE ticker='TRI';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('TRI', date('now'), 66, 'Thomson Reuters 57% vom Hoch aber proprietaere Legal/Tax-Daten als Moat. RBC Upgrade Outperform/$126. JPMorgan cut auf $100. Claude Legal-AI Bedrohung. PE 24 + 3% Dividende.', '{"fundamentals":{"kgv":6,"umsatz":4,"marge":6,"schulden":5,"total":21},"technicals":{"52w_abstand":7,"preistrend":6,"volumen":6,"total":19},"narrativ":{"these":7,"analysten":4,"katalysator":5,"total":16},"sentiment":{"upgrades":3,"insider":2,"social":3,"total":8},"bonus":{"multi_katalysator":2,"institutionell":2,"sektor":1,"total":5},"basis_score":69,"final_score":66}', '[{"level":"moderate","rule":"Claude Legal-AI Bedrohung","penalty":-3}]');

-- TT — Trane Technologies (Score: 68)
UPDATE watchlist SET overall_score=68, overall_reasoning='Trane uebernahm LiquidStack und Stellar Energy fuer Direct-to-Chip und Immersion-Kuehlung und hat einen Rekord-Backlog von $7.8B mit Applied Bookings +120%. Die 2026-Guidance zeigt 6-7% organisches Wachstum mit EPS $14.65-$14.85 (+12-14%). 67% der Analysten sind bullish mit Avg Target $493, aber Wells Fargo hat ein kontraeres Underweight/$400. P/E 35x ist eine Premium-Bewertung die NVIDIA-Vera-Rubin-Chip-Risiko (weniger Kuehlung noetig) nicht einpreist.', score_breakdown='{"fundamentals":{"kgv":5,"umsatz":5,"marge":6,"schulden":5,"total":21},"technicals":{"52w_abstand":4,"preistrend":5,"volumen":4,"total":13},"narrativ":{"these":7,"analysten":5,"katalysator":6,"total":18},"sentiment":{"upgrades":4,"insider":3,"social":3,"total":10},"bonus":{"multi_katalysator":3,"institutionell":2,"sektor":3,"total":8},"basis_score":70,"final_score":68}', star_violations='[]' WHERE ticker='TT';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('TT', date('now'), 68, 'Trane LiquidStack + Stellar Energy Akquisitionen. Rekord-Backlog $7.8B, Applied Bookings +120%. P/E 35x Premium. Vera-Rubin-Chip koennte Kuehlbedarf senken.', '{"fundamentals":{"kgv":5,"umsatz":5,"marge":6,"schulden":5,"total":21},"technicals":{"52w_abstand":4,"preistrend":5,"volumen":4,"total":13},"narrativ":{"these":7,"analysten":5,"katalysator":6,"total":18},"sentiment":{"upgrades":4,"insider":3,"social":3,"total":10},"bonus":{"multi_katalysator":3,"institutionell":2,"sektor":3,"total":8},"basis_score":70,"final_score":68}', '[]');

-- VRSK — Verisk Analytics (Score: 54)
UPDATE watchlist SET overall_score=54, overall_reasoning='Verisk hat eine monopolartige Stellung bei Versicherungsdaten mit einer ueber Jahrzehnte gewachsenen, praktisch nicht replizierbaren Datenbank. KI verstaerkt diesen Moat eher als ihn zu bedrohen. Allerdings hat die Aktie 36% vom 52W-Hoch verloren, der Konsens ist nur Hold, und das langsame Wachstum von ~7% rechtfertigt keine schnelle Erholung. Das Kursziel von $266 bietet 28% Upside, aber kurzfristig fehlen Katalysatoren.', score_breakdown='{"fundamentals":{"kgv":5,"umsatz":4,"marge":6,"schulden":5,"total":20},"technicals":{"52w_abstand":6,"preistrend":4,"volumen":4,"total":14},"narrativ":{"these":6,"analysten":3,"katalysator":3,"total":12},"sentiment":{"upgrades":2,"insider":3,"social":2,"total":7},"bonus":{"multi_katalysator":1,"institutionell":2,"sektor":1,"total":4},"basis_score":57,"final_score":54}', star_violations='[{"level":"moderate","rule":"Hold-Konsens und langsames Wachstum ~7%","penalty":-3}]' WHERE ticker='VRSK';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('VRSK', date('now'), 54, 'Verisk Monopol Versicherungsdaten. KI staerkt Moat. Aber 36% unter Hoch, Hold-Konsens, langsames Wachstum 7%. Kursziel $266 (+28%).', '{"fundamentals":{"kgv":5,"umsatz":4,"marge":6,"schulden":5,"total":20},"technicals":{"52w_abstand":6,"preistrend":4,"volumen":4,"total":14},"narrativ":{"these":6,"analysten":3,"katalysator":3,"total":12},"sentiment":{"upgrades":2,"insider":3,"social":2,"total":7},"bonus":{"multi_katalysator":1,"institutionell":2,"sektor":1,"total":4},"basis_score":57,"final_score":54}', '[{"level":"moderate","rule":"Hold-Konsens langsam","penalty":-3}]');

-- VRT — Vertiv Holdings (Score: 84)
UPDATE watchlist SET overall_score=84, overall_reasoning='Vertiv ist der Picks-and-Shovels-King der AI-Infrastruktur mit organischen Orders +252% YoY, $15B Backlog (verdoppelt), und einer 2026-Guidance die alle Erwartungen zerschmettert (Revenue $13.25-13.75B vs $12.39B est). 100% der 12 Analysten sind bullish mit Kurszielen bis $290 (Mizuho), und die NVIDIA-Partnerschaft fuer modulare AI-Datacenter-Loesungen staerkt die Position. Die Aktie surgte 24.5% nach Earnings und die S&P 500-Aufnahme steht bevor. Einziges Risiko: Hyperscaler koennten eigene Kuehlung entwickeln.', score_breakdown='{"fundamentals":{"kgv":5,"umsatz":7,"marge":6,"schulden":5,"total":23},"technicals":{"52w_abstand":5,"preistrend":6,"volumen":7,"total":18},"narrativ":{"these":8,"analysten":6,"katalysator":6,"total":20},"sentiment":{"upgrades":5,"insider":3,"social":5,"total":13},"bonus":{"multi_katalysator":4,"institutionell":3,"sektor":3,"total":10},"basis_score":84,"final_score":84}', star_violations='[]' WHERE ticker='VRT';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('VRT', date('now'), 84, 'Vertiv Picks-and-Shovels-King: Orders +252%, $15B Backlog, Guidance zerschmettert Erwartungen. 100% bullish, NVIDIA-Partnerschaft. S&P 500 Aufnahme bevor. Risiko: Hyperscaler eigene Kuehlung.', '{"fundamentals":{"kgv":5,"umsatz":7,"marge":6,"schulden":5,"total":23},"technicals":{"52w_abstand":5,"preistrend":6,"volumen":7,"total":18},"narrativ":{"these":8,"analysten":6,"katalysator":6,"total":20},"sentiment":{"upgrades":5,"insider":3,"social":5,"total":13},"bonus":{"multi_katalysator":4,"institutionell":3,"sektor":3,"total":10},"basis_score":84,"final_score":84}', '[]');

-- YASKF — Yaskawa Electric (Score: 50)
UPDATE watchlist SET overall_score=50, overall_reasoning='Yaskawa ist der Weltmarktfuehrer bei Servomotoren — dem Herzstueck jedes Roboters — mit ueber 20% Betriebsmarge und Expansion im Cobot-Segment. Allerdings zeigt die Aktie null Momentum (flat bei $30.73 ueber Wochen), die OTC-Liquiditaet ist mit 1.000 Shares minimal, und es fehlen aktuelle Katalysatoren oder Earnings-Daten. Das Yen-Risiko und die zyklische Fabrikautomatisierung belasten zusaetzlich, weshalb Yaskawa trotz solider langfristiger These kurzfristig unattraktiv bleibt.', score_breakdown='{"fundamentals":{"kgv":5,"umsatz":4,"marge":6,"schulden":5,"total":20},"technicals":{"52w_abstand":4,"preistrend":2,"volumen":1,"total":7},"narrativ":{"these":6,"analysten":2,"katalysator":4,"total":12},"sentiment":{"upgrades":2,"insider":3,"social":2,"total":7},"bonus":{"multi_katalysator":2,"institutionell":1,"sektor":3,"total":6},"basis_score":52,"final_score":50}', star_violations='[]' WHERE ticker='YASKF';
INSERT OR REPLACE INTO score_history (ticker, date, overall_score, reasoning, components, star_violations) VALUES ('YASKF', date('now'), 50, 'Yaskawa Servomotor-Weltmarktfuehrer. Null OTC-Momentum. 1.000 Shares Volumen. Solide These aber kurzfristig unattraktiv.', '{"fundamentals":{"kgv":5,"umsatz":4,"marge":6,"schulden":5,"total":20},"technicals":{"52w_abstand":4,"preistrend":2,"volumen":1,"total":7},"narrativ":{"these":6,"analysten":2,"katalysator":4,"total":12},"sentiment":{"upgrades":2,"insider":3,"social":2,"total":7},"bonus":{"multi_katalysator":2,"institutionell":1,"sektor":3,"total":6},"basis_score":52,"final_score":50}', '[]');
